export const FETCH_IMAGES_BEGIN = "FETCH_IMAGES_BEGIN";
export const FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS";
export const FETCH_IMAGES_FAILURE = "FETCH_IMAGES_FAILURE";
export const FETCH_IMAGE_BEGIN = "FETCH_IMAGE_BEGIN";
export const FETCH_IMAGE_SUCCESS = "FETCH_IMAGE_SUCCESS";
export const FETCH_IMAGE_FAILURE = "FETCH_IMAGE_FAILURE";
